// Database operations for recommendation history

import RecommendationSession, {
    IRecommendationSession,
    IRecommendationSessionDocument,
} from '../models/recommendation-history-model';
import { Types } from 'mongoose';

// createdAt and updatedAt are generated by Mongoose, so callers should not need to provide them
type CreateRecommendationSessionData = Omit<
    IRecommendationSession,
    'createdAt' | 'updatedAt'
>;

export default class RecommendationHistoryRepository {
    // Save a newly generated recommendation session.
    async create(
        sessionData: CreateRecommendationSessionData,
    ): Promise<IRecommendationSessionDocument> {
        const session = new RecommendationSession(sessionData);
        return await session.save();
    }

    // Find recommendation session by ID.
    async findById(
        sessionId: string,
    ): Promise<IRecommendationSessionDocument | null> {
        return await RecommendationSession.findById(sessionId).exec();
    }

    // Find a user's recent recommendation sessions
    async findRecentByUser(
        userId: string,
        limit: number,
    ): Promise<IRecommendationSessionDocument[]> {
        return await RecommendationSession.find({
            userId: new Types.ObjectId(userId),
        })
            .sort({ createdAt: -1 })
            .limit(limit)
            .exec();
    }

    // Record the candidate station selected by the user.
    async recordSelection(
        sessionId: string,
        stationId: string,
        selectedAt: Date = new Date(),
    ): Promise<IRecommendationSessionDocument | null> {
        return await RecommendationSession.findByIdAndUpdate(
            sessionId,
            {
                $set: {
                    'selection.stationId': new Types.ObjectId(stationId),
                    'selection.selectedAt': selectedAt,
                },
            },
            {
                new: true,
                runValidators: true,
            },
        ).exec();
    }
}