import { Request, Response } from "express";
import PredictController from "../../src/controllers/predict-controller";
import PredictService from "../../src/services/predict-service";

// Mock the Service
jest.mock("../../src/services/predict-service");

// Outer describe block for the file/module
describe("PredictController", () => {

    // Inner describe block for the specific function being tested
    describe("getDemandForecast", () => {

        let controller: PredictController;
        let mockService: jest.Mocked<PredictService>;
        let mockRequest: Partial<Request>;
        let mockResponse: Partial<Response>;

        beforeEach(() => {
            mockService = new PredictService() as jest.Mocked<PredictService>;
            controller = new PredictController(mockService);
            mockResponse = {
                status: jest.fn().mockReturnThis(),
                json: jest.fn().mockReturnThis(),
            };
        });

        test("Should reject invalid postcode with 400", async () => {
            // Arrange
            mockRequest = { body: { postcode: "ABC", date: "2025-12-01" } };

            // Act
            await controller.getDemandForecast(mockRequest as Request, mockResponse as Response);

            // Assert
            expect(mockResponse.status).toHaveBeenCalledWith(400);
            expect(mockResponse.json).toHaveBeenCalledWith(expect.objectContaining({
                message: expect.stringMatching(/Invalid Postcode/i)
            }));
        });

        test("Should return success when Service returns valid data", async () => {
            // Arrange
            mockRequest = { body: { postcode: "3000", date: "2025-12-01" } };
            mockService.getDemandForecast.mockResolvedValue({
                postcode: "3000",
                date: "2025-12-01",
                predictedDemandKwh: 45.5,
                isFallback: false,
                message: "Prediction successfully generated by ML service."
            });

            // Act
            await controller.getDemandForecast(mockRequest as Request, mockResponse as Response);

            // Assert
            expect(mockResponse.status).toHaveBeenCalledWith(200);
            expect(mockResponse.json).toHaveBeenCalledWith(expect.objectContaining({
                message: "Demand forecast retrieved successfully",
                data: expect.objectContaining({
                    predictedDemandKwh: 45.5,
                    isFallback: false
                })
            }));
        });

        test("Should return 200 with fallback data when Service triggers fallback", async () => {
            // Arrange
            mockRequest = { body: { postcode: "3000", date: "2025-12-01" } };
            mockService.getDemandForecast.mockResolvedValue({
                postcode: "3000",
                date: "2025-12-01",
                predictedDemandKwh: 50.0,
                isFallback: true,
                message: "External weather API lag detected. Using baseline fallback."
            });

            // Act
            await controller.getDemandForecast(mockRequest as Request, mockResponse as Response);

            // Assert
            expect(mockResponse.status).toHaveBeenCalledWith(200);
            expect(mockResponse.json).toHaveBeenCalledWith(expect.objectContaining({
                message: "Demand forecast retrieved successfully",
                data: expect.objectContaining({
                    isFallback: true
                })
            }));
        });
    });
});